# Docker compose file with postgres database

version: '3.1'
services:
    db:
      image: postgres
      restart: always
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: password
        POSTGRES_DB: meetup
      ports:
      - "5432:5432"